In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load the CSV file
df = pd.read_csv('AllNegative_0424_NewNames.csv')

In [3]:
# Assume the two columns are 'Column1' and 'Column2', and the certain value is 'value'
# Replace values less than 'value' with NaN
dfH = df.loc[:,'Cornell_Pos_S-01_LMT_PS_PMM_R0':'Cornell_Pos_S-50_LMH_LCT_PS_PMM_R1']
dfH[dfH < 10000] = np.nan

In [4]:
dfH.head()

,Cornell_Pos_S-01_LMT_PS_PMM_R0,Cornell_Pos_S-01_LMT_PS_PMM_R1,Cornell_Pos_S-03_LCC_PS_R0,Cornell_Pos_S-03_LCC_PS_R1,Cornell_Pos_S-04_LMT_PS_PMM_R0,Cornell_Pos_S-04_LMT_PS_PMM_R1,Cornell_Pos_S-05_O_R0,Cornell_Pos_S-05_O_R1,Cornell_Pos_S-06_O_R0,Cornell_Pos_S-06_O_R1,...,Cornell_Pos_S-44_O_R0,Cornell_Pos_S-44_O_R1,Cornell_Pos_S-46_O_R0,Cornell_Pos_S-46_O_R1,Cornell_Pos_S-48_O_R0,Cornell_Pos_S-48_O_R1,Cornell_Pos_S-49_O_R0,Cornell_Pos_S-49_O_R1,Cornell_Pos_S-50_LMH_LCT_PS_PMM_R0,Cornell_Pos_S-50_LMH_LCT_PS_PMM_R1
0,1226234.0,385427.0,2849758.0,537862.0,5653096.0,201624.0,3811464.0,286522.0,6517214.0,1070008.0,...,1431009.0,379703.0,585250.0,350752.0,774496.0,564311.0,622496.0,299630.0,1249109.0,4701936.0
1,426166.0,441196.0,1075231.0,260201.0,1257630.0,324608.0,984744.0,270604.0,539779.0,222636.0,...,1304241.0,183173.0,929380.0,593572.0,1090018.0,221511.0,1137719.0,202271.0,820458.0,615065.0
2,1095311.0,147112.0,1519413.0,183373.0,4244216.0,434381.0,938750.0,432076.0,2680426.0,491228.0,...,1558775.0,263064.0,1296370.0,369637.0,632704.0,410300.0,1518908.0,336420.0,1456780.0,185133.0
3,1037785.0,433319.0,542909.0,494895.0,1643726.0,256550.0,1599949.0,88459.0,2572903.0,347992.0,...,718475.0,159556.0,611433.0,130901.0,241054.0,56127.0,45035.0,335248.0,531862.0,442484.0
4,495960.0,179603.0,104798.0,70518.0,139255.0,77115.0,185114.0,76044.0,110832.0,104837.0,...,927563.0,445428.0,851633.0,260781.0,439004.0,360436.0,524498.0,296867.0,1521599.0,73443.0

In [5]:
# Save the dataframe to a new CSV file
dfH.to_csv('10000Max_NonAvg+NaN_Neg.csv', index=False)