In [56]:
import pandas as pd
import matplotlib.pyplot as plt

In [57]:
data = pd.read_csv('Mass+Intensity.csv')

In [58]:
data.head()

,A,A.1,A.2,A.3,A.4,A.5,A.6,A.7,A.8,A.9,...,A.193,A.194,A.195,A.196,A.197,A.198,A.199,A.200,A.201,A.202
0,"6,10a-dihydroxy-4-(hydroxymethyl)-4,7,11b-trim...",52.89857,67.05452,67.89941,69.07005,71.01316,71.04950,79.05457,81.07009,83.08576,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MS/MS,50315.00000,69571.00000,54155.00000,57415.00000,68976.00000,88785.00000,135205.00000,470703.00000,71977.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"6,10a-dihydroxy-4-(hydroxymethyl)-4,7,11b-trim...",62.77433,67.05455,69.07013,71.01306,71.04927,75.02482,79.05457,79.73860,81.07013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MS/MS,13492.00000,18079.00000,39842.00000,43853.00000,14189.00000,13493.00000,35254.00000,12288.00000,164399.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"6,10a-dihydroxy-4-(hydroxymethyl)-4,7,11b-trim...",55.01813,67.05452,67.34754,69.07032,71.01311,79.05445,81.07013,83.08569,85.06506,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
for i in range (0, 187, 2):
    x = data.iloc[i].values[1:]  # This gets the first row
    y = data.iloc[i+1].values[1:]  # This gets the second row

    # Create scatter plot
    plt.scatter(x, y, label='Data Points', color='dimgray', s=1)
    plt.xlim(50,400)
    # Add vertical lines from the x-axis to each data point
    for xi, yi in zip(x, y):
        plt.vlines(xi, 0, yi, colors='black', linestyles='solid', alpha=0.7)

    # Add labels and title
    plt.xlabel('m/z')
    plt.ylabel('Intensity')
    plt.title(data.iloc[i].values[0])
    plt.xlim(50,500)
    #plt.ylim(0,max)
    #plt.legend()

    # Save the plot
    plt.savefig(f"{data.iloc[i].values[0]+str(i)}.png", dpi=300)

    # Clear the current figure's content for the next plot
    plt.clf()

C:\Users\JOHNST47\AppData\Local\anaconda3\Lib\site-packages\matplotlib\axes\_base.py:2503: UserWarning: Warning: converting a masked element to nan.
  xys = np.asarray(xys)